id = "nova-theme"
name = "Nova"
version = "0.1.0"
schema_version = 1
authors = ["Peng Lyu <penn.lv@gmail.com>","Ming Jiang <jm1179356055@gmail.com>"]
description = "Nova color scheme for Zed, ported from VSCode"
repository = "https://github.com/overstarry/zed-nova"
